<script>
	import Description from '$lib/components/description.svelte';
	import src from '$lib/assets/marcel-marceau.jpg';
</script>
<div class='virtual-body w-full h-full m-0 p-0'>
	<h1 id='title'>Marcel Marceau</h1>
	<figure id='img-div'>
		<img id='image' {src} alt="Marcel Marceau in a chair facing towards the reader" />
		<figcaption
			id='img-caption'>Marcel Marceau posing at us in a red cushy chair.
		Hands holding a hat that lay upon his lap.</figcaption>
	</figure>

	<div id='tribute-info' class='flex-container'>
		<Description date={'March 22, 1923'}
								 summary={'He was born in Strasbourg, France.'} />
		<Description date={1939}
								 summary={'He participated in World War 2 in the French Resistance against the German-occupied France.'} />
		<Description date={'1947'}
								 summary={'He created Bip the clown and mimed as that character. It first appeared in the Theatre de Poche.'} />
		<Description date={'1949'}
								 summary={'Performed in many mimodramas with companies of his own.'} />
		<Description date={'September 22, 2007'}
								 summary={'Marcel Marceau died at age 84 in Cahors, France.'} />
		<Description date={'1986'}
								 summary={'He received the highest honours from France which was the Officier de la Legion d\'Honneur'} />
		<Description date={'1997, 2005'}
								 summary={'Marceau\'s last mimodrama was Le chapeau Melon & he retired in 2005.'} />
		<Description date={'March 22nd, 2023'}
								 summary={'Google\'s Doodle celebrated him.'} />
	</div>

	<blockquote class='container' cite='https://forbes.com/quote/6447'>
		<p>"Do not the most moving moments of our lives find us without words?"</p>
		<p>- Marcel Marceau</p>
	</blockquote>


	<p>For more information, see <a id='tribute-link' rel='noreferrer'
										href='https://en.wikipedia.org/wiki/Marcel_Marceau'
		 target='_blank'>Marcel Marceau's biography on Wikipedia</a></p>
</div>

<style>
    @import url('https://fonts.googleapis.com/css2?family=Cabin&family=Raleway:wght@500&display=swap');
		.virtual-body {
				background-color: rgb(180, 180, 200);
				/* Generated by Copilot */
				/*width: 100%;*/
				/*height: 100%;*/
				/*margin: 0;*/
				/*padding: 0;*/

				font-size: 16px;
		}
		h1 {
				font-family: 'Cabin', sans-serif;
				font-size: 3rem;
				text-align: center;
		}
		p, figcaption {
				font-family: 'Raleway', sans-serif;
				font-size: 1.5rem;
				text-align: center;
				padding-top: 20px;
				padding-bottom: 20px;
		}

    .flex-container, .container, img {
        margin-left: auto;
        margin-right: auto;
    }

		figure {
				background-color: rgb(210, 210, 220);
				width: 100%;
		}
		img {
				max-width: 100%;
		}

		.flex-container {
				margin-top: 20px;
        /*background-color: rgb(180, 180, 200);*/
				display: flex;
				flex-direction: row;
        flex-wrap: wrap;
				justify-content: center;
				width: 620px;

        border: 10px outset rgb(150, 150, 180);
				/*gap: 16px;*/
		}

		blockquote {
				height: auto;
				margin: auto;
				margin-top: 20px;
				padding: 10px;
		}


		a {
				color: rgb(50, 50, 200);
		}
    a:hover {
        color: rgb(50, 100, 255);
    }
		a:active {
        color: rgb(130, 130, 200);
		}

		.container {
				width: 400px;
        background-color: rgb(230, 230, 240);
				border: 10px outset rgb(150, 150, 180);
		}
</style>